version: '3.8'

services:
    nginx:
        image: nginx:1.25-alpine
        container_name: nginx-${PROJECT_NAME}
        restart: unless-stopped
        ports:
            - ${HTTP_PORT}:80
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d/
            - php_socket:/var/run/php
            - .:/var/www/html
        depends_on:
            - php
        networks:
            - symfony


    php:
        container_name: php-${PROJECT_NAME}
        build:
            context: docker/.
            args:
                - CACHEBUST=$(date +%s)
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
            - .:/var/www/html
        networks:
            - symfony

volumes:
    php_socket:

networks:
    symfony:
        name: symfony-${PROJECT_NAME}
